apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: test-app
  name: test-app
spec:
  template:
    spec:
      containers:
      - name: test-app
        lifecycle:
          preStop:
            exec:
              command: ["sleep","15"]
