apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: test-app
  name: test-app
spec:
  template:
    spec:
      containers:
      - name: test-app
        readinessProbe:
          periodSeconds: 2
          httpGet:
            path: /
            port: 6969
